//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBolsaTrabajo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfcReclutamiento
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
