//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBolsaTrabajo3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataBaseSAGAEntities : DbContext
    {
        public DataBaseSAGAEntities()
            : base("name=DataBaseSAGAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prioridad> Prioridad { get; set; }
        public virtual DbSet<OfcReclutamiento> OfcReclutamiento { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int usp_InsertarProblema(string email, string commentary)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var commentaryParameter = commentary != null ?
                new ObjectParameter("Commentary", commentary) :
                new ObjectParameter("Commentary", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarProblema", emailParameter, commentaryParameter);
        }
    }
}
